# 设置语言
language: node_js
# 指定需要sudo权限
sudo: required
# 设置相应版本
node_js: stable
install:
   # 安装hexo及插件
   - npm install -g hexo-cli
script:
   # 清除
   - hexo clean
   # 生成
   - hexo g
after_script:
  - git config user.name "guqiangjs"
  - git config user.email "guqiangjs@gmail.com"
  # 替换同目录下的_config.yml文件中gh_token字符串为travis后台刚才配置的变量，注意此处sed命令用了双引号。单引号无效！
  - sed -i "s/gh_token/${GITHUB_TOKEN}/g" ./_config.yml
  - hexo deploy