# 设置语言
language: node_js
# 指定需要sudo权限
sudo: required
# 设置相应版本
node_js: stable
install:
   # 安装hexo及插件
   - npm install -g hexo-cli
script:
   # 清除
   - hexo clean
   # 生成
   - hexo g
after_script:
   - cd public
   - git init
   - git config user.name "guqiangjs"
   - git config user.email "guqiangjs@gmail.com"
   - git add .
   - git commit -m "Update docs"
   - git push --force --quiet "https://${GITHUB_TOKEN}@${GIT_PAGE_REF}" master:master
